# Generated by Django 4.1.3 on 2022-12-02 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import my_account.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=80)),
                ('size', models.TextField(max_length=80)),
                ('extension', models.TextField(max_length=80)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_url', models.FileField(blank=True, null=True, upload_to=my_account.models.upload_to)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
