# Generated by Django 4.1.3 on 2022-12-02 04:24

from django.db import migrations, models
import django.utils.timezone
import utils.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0003_rename_image_url_files_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_activated',
        ),
        migrations.AlterField(
            model_name='files',
            name='file_url',
            field=models.FileField(default=django.utils.timezone.now, upload_to=utils.models_utils.upload_to, validators=[utils.models_utils.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='size',
            field=models.TextField(max_length=80, validators=[utils.models_utils.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
